### ISSUE TITLE
log -n, log -f

### ISSUE THREAD

**Issue by substack** [substack/psy#1]
Instead of just live updates, there should probably be the same options as tail: `-f` and `-n`.

**Comment by erbridge** [comment]
It would be useful to be able to see the history.

**Comment by substack** [comment]
Added in 1.5.0. `psy log` now accepts `-n I`, `-n I,J`, `-N I`, and `-N I,J` to slice lines from the log starting from the start (`-N`) or the end (`-n`) of the file.
