### ISSUE TITLE
Restart process on reboot

### ISSUE THREAD

**Issue by tnguyen14** [substack/psy#15]
When I reboot a machine, the psy processes are not automatically restarted, until I run `psy ls`. After that, the processes will come back. 

Is this the right behavior, or should they be automatically restarted on reboot?

**Comment by aredridel** [comment]
There's no automatic provision for a start at boot. In my startup, I have `psy daemon` (I actually do it with a crontab)

```
@reboot psy daemon
```

**Comment by karissa** [comment]
This should probably be reflected in the docs, nice catch..

**Comment by tnguyen14** [comment]
Thanks for that @aredridel. Will do the same.

In the case of a multi-user machine, will that work for all the different users as well?

**Comment by tnguyen14** [comment]
I created a PR to add this to the docs. Feel free to let me know if the wording should be updated if it's not clear enough.
