### ISSUE TITLE
calling `psy start` multiple times doesn't override older config

### ISSUE THREAD

**Issue by maxogden** [substack/psy#7]
was my first time using psy and I got confused by this behavior. If you do e.g. `psy start -n foo -- blah blah`, and you got your config wrong and you go to tweak it again, e.g.:

```
psy stop foo
psy start -n foo -- blah blah blah blah
```

then what seems to happen is the 2nd `psy start` silently fails and doesn't overwrite the existing `foo` entry in psy's process list, so to update the configuration you have to first do `psy rm foo` and then do `psy start` to load the new settings

proposal: if you try and start a thing that already exists w/ new options after `--`, it should update the options in the psy list with whatever stuff you put after `--`

**Comment by substack** [comment]
Fixed in 1.6.0:

If you try to start a process with the same name as a running process, you get an error message:

    A process called "time" is already running.

and if you try to start a process with the same name as a non-running process, the old process gets auto-removed so your new settings will take over for that name.
