### ISSUE TITLE
psy@1.6.1 seems broken with node@4.2.1 LTS

### ISSUE THREAD

**Issue by danieljuhl** [substack/psy#8]
When I run `psy start ...` or `psy ls` I get the following:
```
Error: exited with code: 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/psy/node_modules/auto-daemon/index.js:59:12)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Downgrading to `psy@<=1.6.0` and everything works...

**Comment by substack** [comment]
What command are you trying with `psy start` that worked before?

**Comment by danieljuhl** [comment]
psy start --name=app --maxRestarts=5 --logfile=/var/log/app.stdout.log --env.NODE_ENV=production -- node server.js

**Comment by danieljuhl** [comment]
I haven't tried with `1.5.0`, but I'll test it later today.

**Comment by sjonnet19** [comment]
Same for me. 1.6.1 does not start any services/servers.

**Comment by yoshuawuyts** [comment]
Can confirm, `psy@latest` doesn't seem to work as expected. Tested on Node `v0.10`, `v0.12` and `v4`. Getting variations on:
```js
// index.js
console.log('hello world')
```
```txt
❯ psy start -- node index.js
Error: exited with code: 8
    at ChildProcess.<anonymous> (/Users/yw/.nvm/v0.10.40/lib/n
ode_modules/psy/node_modules/auto-daemon/index.js:59:12)
    at ChildProcess.g (events.js:180:16)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:8
20:12)
```
For some reason `auto-daemon` spawn exits with a statusCode of `8`. Did a search about what this could mean, but couldn't find anything. Hope this report helps. Thanks!

**Comment by yoshuawuyts** [comment]
`git bisect` results:
- c7377c70d4218c7ddaf92079c381abf966b491f8 - `psy start` works, everything seems to work. Had a crash once on `psy ls`, but couldn't reproduce.
- 3dfa0a5 - seems alright
- f8e76dc51cd73c2769812b90bd279de0333bfee7 - seems alright
- 93d8e7d939446bb502310f4a10e8b8639a70d931 - should be the culprit.

__edit__ realized I installed the `inherits` package in between, seems to be missing the dep which was throwing the error. Writing a PR now.
